// AUTO-GENERATED by scripts/build-tokens.mjs — 勿手改
// 风格包注册表（规范第九节）。供设置页枚举，以及 ThemeService 运行时 inline 注入包 token
// （必须由 ThemeService 注入：它会 inline 写 --radius-*/--shadow-*/--font-*/语义色，
//   inline 优先级高于任何样式块，故风格包值只能在主题变量之后再次 inline 注入才能生效）。
// 源：packages/design-system/styles/<id>/

export interface StylePackMeta {
  id: string;
  name: string;
  description: string;
  order: number;
  isDefault: boolean;
}

/** 各风格包 token 覆盖（CSS 变量名 → 已解析字面值） */
export interface StylePackTokenMap {
  /** 全模式覆盖 */
  base: Record<string, string>;
  /** 仅亮色档覆盖 */
  light: Record<string, string>;
  /** 仅暗色档覆盖 */
  dark: Record<string, string>;
}

export const stylePacks = [
  {
    id: "xindongfang",
    name: "新东方极简",
    description: "墨为骨，青为神，朱为印，白为息。品牌默认风格，四签名（黛青 / 朱砂 / 衬线 / 宣纸）的持有者。",
    order: 0,
    isDefault: true,
  },
  {
    id: "comic",
    name: "漫画风",
    description: "纸底 + 真黑墨 + 品牌橙。粗黑描边、右下硬投影、手绘感——像一页被墨线框住的分镜纸。",
    order: 10,
    isDefault: false,
  },
] as const;

export type StylePackId = (typeof stylePacks)[number]['id'];

export const DEFAULT_STYLE_PACK_ID: StylePackId = "xindongfang";

export const stylePackTokens: Record<string, StylePackTokenMap> = {
  "xindongfang": {
    "base": {},
    "light": {},
    "dark": {}
  },
  "comic": {
    "base": {
      "--style-stroke-width": "2px",
      "--style-focus-ring": "#F3EAD3",
      "--size-radius-sm": "10px",
      "--size-radius-base": "12px",
      "--size-radius-lg": "15px",
      "--size-radius-xl": "19px",
      "--size-radius-2xl": "22px",
      "--radius-sm": "10px",
      "--radius-base": "12px",
      "--radius-lg": "15px",
      "--radius-xl": "19px",
      "--radius-2xl": "22px",
      "--shadow-xs": "2px 3px 0 var(--color-text-primary)",
      "--shadow-sm": "3px 4px 0 var(--color-text-primary)",
      "--shadow-base": "4px 5px 0 var(--color-text-primary)",
      "--shadow-lg": "5px 6px 0 var(--color-text-primary)",
      "--shadow-xl": "6px 7px 0 var(--color-text-primary)",
      "--shadow-2xl": "8px 9px 0 var(--color-text-primary)",
      "--font-family-serif": "'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'SF Pro Display', Roboto, sans-serif",
      "--font-weight-semibold": "700",
      "--font-weight-bold": "800"
    },
    "light": {
      "--color-bg-base": "#FFF4DD",
      "--color-bg-sunken": "#F7E9C9",
      "--color-bg-card": "#FFFDF7",
      "--color-bg-overlay": "#FFFEFB",
      "--color-bg-modal": "#FFFEFB",
      "--color-bg-workbench": "#F8ECD1",
      "--color-bg-scene": "#FAF1DA",
      "--color-bg-tooltip": "#FFFDF7",
      "--color-text-primary": "#29261F",
      "--color-text-secondary": "#69614F",
      "--color-text-muted": "#8B8270",
      "--color-text-disabled": "#ADA48F",
      "--color-accent-50": "#FCEBDD",
      "--color-accent-100": "#F7D2B8",
      "--color-accent-200": "#EDA87E",
      "--color-accent-300": "#E0703A",
      "--color-accent-400": "#D2521B",
      "--color-accent-500": "#B8461A",
      "--color-accent-600": "#9E3A12",
      "--color-accent-700": "#85300E",
      "--color-accent-800": "#6A260A",
      "--color-accent-foreground": "#FFFDF7",
      "--color-brand-seal": "#A8382A",
      "--color-brand-seal-foreground": "#FFFDF7",
      "--color-brand-seal-hover": "#8E2E22",
      "--color-success-solid": "#1F7A4D",
      "--color-success-bg": "rgba(31, 122, 77, 0.14)",
      "--color-success-border": "rgba(31, 122, 77, 0.55)",
      "--color-warning-solid": "#8A6000",
      "--color-warning-bg": "rgba(138, 96, 0, 0.14)",
      "--color-warning-border": "rgba(138, 96, 0, 0.55)",
      "--color-error-solid": "#B3261E",
      "--color-error-bg": "rgba(179, 38, 30, 0.14)",
      "--color-error-border": "rgba(179, 38, 30, 0.55)",
      "--color-info-solid": "#17658B",
      "--color-info-bg": "rgba(23, 101, 139, 0.12)",
      "--color-info-border": "rgba(23, 101, 139, 0.50)",
      "--color-highlight-solid": "#FFE071",
      "--color-highlight-bg": "rgba(255, 224, 113, 0.40)",
      "--color-overlay": "rgba(41, 38, 31, 0.45)",
      "--color-feedback-star": "#D9A400",
      "--element-bg-subtle": "rgba(41, 38, 31, 0.06)",
      "--element-bg-soft": "rgba(41, 38, 31, 0.09)",
      "--element-bg-base": "rgba(41, 38, 31, 0.12)",
      "--element-bg-medium": "rgba(41, 38, 31, 0.18)",
      "--element-bg-strong": "rgba(41, 38, 31, 0.26)",
      "--element-bg-elevated": "rgba(41, 38, 31, 0.10)",
      "--border-subtle": "rgba(41, 38, 31, 0.35)",
      "--border-base": "#29261F",
      "--border-medium": "#29261F",
      "--border-strong": "#29261F",
      "--border-prominent": "#29261F",
      "--border-accent-solid": "rgba(184, 70, 26, 0.55)",
      "--border-accent-soft": "rgba(184, 70, 26, 0.45)",
      "--border-accent-subtle": "rgba(184, 70, 26, 0.25)",
      "--border-accent-strong": "rgba(184, 70, 26, 0.75)",
      "--card-bg-default": "rgba(255, 253, 247, 0.92)",
      "--card-bg-elevated": "rgba(255, 254, 251, 0.98)",
      "--card-bg-subtle": "rgba(255, 253, 247, 0.70)",
      "--card-bg-hover": "rgba(255, 254, 251, 0.96)",
      "--card-bg-active": "rgba(255, 255, 255, 1.00)",
      "--card-bg-accent": "rgba(184, 70, 26, 0.12)",
      "--card-bg-accent-hover": "rgba(184, 70, 26, 0.20)",
      "--input-bg": "#FFFDF7",
      "--input-bg-hover": "#FFFEFB",
      "--input-bg-focus": "#FFFEFB",
      "--input-bg-disabled": "rgba(41, 38, 31, 0.05)",
      "--scrollbar-thumb": "rgba(41, 38, 31, 0.25)",
      "--scrollbar-thumb-hover": "rgba(41, 38, 31, 0.40)",
      "--modal-overlay": "rgba(41, 38, 31, 0.50)",
      "--badge-accent-bg": "rgba(184, 70, 26, 0.14)",
      "--color-success": "#4ECB8B",
      "--color-warning": "#E8A33D",
      "--color-error": "#FF6B5E",
      "--color-info": "#9FB3D9",
      "--color-highlight": "#FFE071"
    },
    "dark": {
      "--color-bg-base": "#221C14",
      "--color-bg-sunken": "#1B1610",
      "--color-bg-card": "#2C251B",
      "--color-bg-overlay": "#332B20",
      "--color-bg-modal": "#3A3126",
      "--color-bg-workbench": "#191410",
      "--color-bg-scene": "#262019",
      "--color-bg-tooltip": "#3A3126",
      "--color-text-primary": "#F3EAD3",
      "--color-text-secondary": "#D6CCB2",
      "--color-text-muted": "#A79D86",
      "--color-text-disabled": "#7C7462",
      "--color-accent-50": "#3A2418",
      "--color-accent-100": "#4D2E1B",
      "--color-accent-200": "#6B3D20",
      "--color-accent-300": "#B35F2A",
      "--color-accent-400": "#D97636",
      "--color-accent-500": "#E86E2E",
      "--color-accent-600": "#F7A06A",
      "--color-accent-700": "#FBB98D",
      "--color-accent-800": "#FDD3B3",
      "--color-accent-foreground": "#1A150C",
      "--color-brand-seal": "#E0553A",
      "--color-brand-seal-foreground": "#1A150C",
      "--color-brand-seal-hover": "#EF6A4F",
      "--color-success-solid": "#4ECB8B",
      "--color-success-bg": "rgba(78, 203, 139, 0.14)",
      "--color-success-border": "rgba(78, 203, 139, 0.50)",
      "--color-warning-solid": "#E8A33D",
      "--color-warning-bg": "rgba(232, 163, 61, 0.14)",
      "--color-warning-border": "rgba(232, 163, 61, 0.50)",
      "--color-error-solid": "#FF6B5E",
      "--color-error-bg": "rgba(255, 107, 94, 0.14)",
      "--color-error-border": "rgba(255, 107, 94, 0.50)",
      "--color-info-solid": "#9FB3D9",
      "--color-info-bg": "rgba(159, 179, 217, 0.14)",
      "--color-info-border": "rgba(159, 179, 217, 0.45)",
      "--color-highlight-solid": "#FFE071",
      "--color-highlight-bg": "rgba(255, 224, 113, 0.22)",
      "--color-overlay": "rgba(0, 0, 0, 0.70)",
      "--color-feedback-star": "#FFD24A",
      "--element-bg-subtle": "rgba(243, 234, 211, 0.06)",
      "--element-bg-soft": "rgba(243, 234, 211, 0.09)",
      "--element-bg-base": "rgba(243, 234, 211, 0.12)",
      "--element-bg-medium": "rgba(243, 234, 211, 0.18)",
      "--element-bg-strong": "rgba(243, 234, 211, 0.26)",
      "--element-bg-elevated": "rgba(243, 234, 211, 0.10)",
      "--border-subtle": "rgba(243, 234, 211, 0.30)",
      "--border-base": "rgba(243, 234, 211, 0.80)",
      "--border-medium": "rgba(243, 234, 211, 0.90)",
      "--border-strong": "rgba(243, 234, 211, 0.95)",
      "--border-prominent": "rgba(243, 234, 211, 1.00)",
      "--border-accent-solid": "rgba(232, 110, 46, 0.60)",
      "--border-accent-soft": "rgba(232, 110, 46, 0.45)",
      "--border-accent-subtle": "rgba(232, 110, 46, 0.25)",
      "--border-accent-strong": "rgba(232, 110, 46, 0.80)",
      "--card-bg-default": "rgba(243, 234, 211, 0.05)",
      "--card-bg-elevated": "rgba(243, 234, 211, 0.08)",
      "--card-bg-subtle": "rgba(243, 234, 211, 0.03)",
      "--card-bg-hover": "rgba(243, 234, 211, 0.09)",
      "--card-bg-active": "rgba(243, 234, 211, 0.13)",
      "--card-bg-accent": "rgba(232, 110, 46, 0.16)",
      "--card-bg-accent-hover": "rgba(232, 110, 46, 0.26)",
      "--input-bg": "rgba(243, 234, 211, 0.05)",
      "--input-bg-hover": "rgba(243, 234, 211, 0.08)",
      "--input-bg-focus": "rgba(243, 234, 211, 0.08)",
      "--input-bg-disabled": "rgba(243, 234, 211, 0.03)",
      "--scrollbar-thumb": "rgba(243, 234, 211, 0.25)",
      "--scrollbar-thumb-hover": "rgba(243, 234, 211, 0.40)",
      "--modal-overlay": "rgba(0, 0, 0, 0.75)",
      "--badge-accent-bg": "rgba(232, 110, 46, 0.16)",
      "--color-success": "#4ECB8B",
      "--color-warning": "#E8A33D",
      "--color-error": "#FF6B5E",
      "--color-info": "#9FB3D9",
      "--color-highlight": "#FFE071"
    }
  },
};

/** 取某风格包在当前明暗档下应注入的 CSS 变量表（base 打底 + 当前档覆盖） */
export function resolveStylePackTokens(
  id: string,
  mode: 'light' | 'dark',
): Record<string, string> {
  const pack = stylePackTokens[id];
  if (!pack) return {};
  return { ...pack.base, ...pack[mode] };
}
