# /// script
# requires-python = ">=3.10"
# dependencies = ["huggingface_hub>=0.34"]
# ///
"""Sync local model files to ModelScope + HuggingFace and regenerate manifest.json.

Single source of truth is a local models directory (layout matches the remote
repos: asr/..., tts/..., rwkv/..., embedding/...). The script:

1. Regenerates manifest.json (size + sha256 per file; semantic model keys and
   hashes are reused from the previous manifest when the path+size match).
2. Pushes new/changed files to ModelScope via git+LFS (credentials are read
   from ~/.modelscope/credentials).
3. Pushes new/changed files to HuggingFace via huggingface_hub (skipped with
   a warning when the local token lacks write permission).

Usage:
  uv run scripts/sync-models.py --local-dir <models-dir> [--resources-dir dist]
      [--skip-ms] [--skip-hf] [--dry-run]

With --resources-dir the installer resource zips (main/underlay/sounds/
runtime-*.zip produced by desktop-tauri-build.mjs) are uploaded to the
repos under `resources/`. They share the upload channel but are NOT
registered in the model manifest.json — their own
resources-manifest-<os>-<arch>.json (generated by the build script) is
the consumer-side contract.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

HF_REPO = "cgisky/ai00-x"
MS_REPO = "cgisky/Ai00-X"
MS_API_FILES = (
    f"https://modelscope.cn/api/v1/models/{MS_REPO}/repo/files"
    "?Revision=master&Recursive=true"
)
MANIFEST_HOSTS = {
    "ms": {
        "name": "ModelScope",
        "base": f"https://modelscope.cn/models/{MS_REPO}/resolve/master",
    },
    "hf": {"name": "HuggingFace", "base": f"https://huggingface.co/{HF_REPO}/resolve/main"},
}
# Files larger than this must go through git LFS on the ModelScope repo.
LFS_THRESHOLD = 50 * 1024 * 1024

# Components/files that are uploaded to the repos but NOT registered in
# manifest.json. They are optional large downloads managed by their own
# on-demand downloaders:
# - acestep: ~14.2 GB of presets, downloaded only when the user picks one
#   (acestep_download_preset; also pulls the ASR aligner as a companion).
# - ASR forced-aligner: acestep companion, fetched together with a preset.
# sa3 IS registered (first-launch download, ~1.6 GB) per product decision.
MANIFEST_EXCLUDE_COMPONENTS = {"acestep", "resources"}
MANIFEST_EXCLUDE_FILES = {"asr/qwen3-forced-aligner-0.6b-q8_0.gguf"}

# Installer resource zips uploaded under resources/ (see --resources-dir).
RESOURCE_FILES = {"main.zip", "underlay.zip", "sounds.zip"}


def log(msg: str) -> None:
    print(f"[sync-models] {msg}", flush=True)


def run(cmd: list[str], cwd: Path | None = None, env: dict | None = None) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(cmd[:3])} ...\nstderr: {proc.stderr[-2000:]}"
        )
    return proc


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(4 * 1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def collect_local_files(local_dir: Path) -> dict[str, int]:
    """Map repo-relative path -> size for model files (manifest.json excluded).

    Hidden dirs (.cache, .git, ...) are skipped — e.g. huggingface_hub leaves
    a `.cache/` inside snapshot-style model dirs.
    """
    files: dict[str, int] = {}
    for p in sorted(local_dir.rglob("*")):
        if not p.is_file() or p.name == "manifest.json":
            continue
        rel = p.relative_to(local_dir)
        if any(part.startswith(".") for part in rel.parts):
            continue
        files[rel.as_posix()] = p.stat().st_size
    return files


def collect_resource_files(resources_dir: Path) -> dict[str, int]:
    """Installer resource zips from the build dist dir, mapped to resources/<file>."""
    files: dict[str, int] = {}
    for p in sorted(resources_dir.iterdir()):
        if not p.is_file():
            continue
        if p.name in RESOURCE_FILES or (p.name.startswith("runtime-") and p.name.endswith(".zip")):
            files[f"resources/{p.name}"] = p.stat().st_size
    return files


def load_existing_manifest(local_dir: Path) -> dict:
    """Previous manifest: local copy first (fresh), then ModelScope (remote)."""
    local = local_dir / "manifest.json"
    if local.exists():
        try:
            return json.loads(local.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass
    try:
        with direct_urlopen(MANIFEST_HOSTS["ms"]["base"] + "/manifest.json", timeout=30) as r:
            return json.loads(r.read().decode("utf-8"))
    except Exception as e:  # noqa: BLE001
        log(f"warn: no previous manifest ({e}); building fresh")
        return {"version": "2.0.0", "components": {}}


def build_manifest(local_dir: Path, files: dict[str, int], prev: dict) -> dict:
    """Index previous entries by url so semantic keys/hashes survive re-syncs.

    MANIFEST_EXCLUDE_* are skipped here (still uploaded, just not registered —
    see the comment at their definition).
    """
    files = {
        p: s
        for p, s in files.items()
        if p.split("/", 1)[0] not in MANIFEST_EXCLUDE_COMPONENTS
        and p not in MANIFEST_EXCLUDE_FILES
    }
    prev_entries: dict[str, tuple[str, dict]] = {}  # url -> (key, entry)
    for comp in prev.get("components", {}).values():
        for key, entry in comp.get("models", {}).items():
            prev_entries[entry["url"]] = (key, entry)

    components: dict[str, dict] = {}
    for path, size in files.items():
        top = path.split("/", 1)[0]
        comp = components.setdefault(top, {"models": {}})
        old_key, old = prev_entries.get(path, (None, None))
        if old and old.get("size") == size:
            # path+size unchanged: reuse the semantic key and cached hash
            entry = dict(old)
            key = old_key
        else:
            key = old_key or Path(path).stem
            base, i = key, 2
            while key in comp["models"]:
                key = f"{base}-{i}"
                i += 1
            entry = {
                "name": Path(path).name,
                "size": size,
                "hash": f"sha256:{sha256_of(local_dir / path)}",
                "url": path,
                "required": bool(old.get("required", True)) if old else True,
            }
        comp["models"][key] = entry

    return {
        "version": prev.get("version", "2.0.0"),
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "components": components,
        "hosts": MANIFEST_HOSTS,
    }


# 无代理 opener：urllib 在 Windows 上会静默读取注册表系统代理（IE 设置），
# 而本地代理（Clash 等）对 Python 的 TLS ClientHello 指纹可能分流失效导致
# SSL EOF。ModelScope/HF 的 API 元数据请求走直连最稳。
_DIRECT_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))


def direct_urlopen(url: str, timeout: int = 30):
    return _DIRECT_OPENER.open(url, timeout=timeout)


def ms_remote_files() -> dict[str, int]:
    with direct_urlopen(MS_API_FILES, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    blobs = data.get("Data", {}).get("Files") or []
    return {f["Path"]: f["Size"] for f in blobs if f.get("Type") == "blob"}


def ms_credentials() -> tuple[str, str]:
    cred = Path.home() / ".modelscope" / "credentials"
    user = (cred / "user").read_text(encoding="utf-8").strip().split(":", 1)[0]
    token = (cred / "git_token").read_text(encoding="utf-8").strip()
    return user, token


def remote_manifest_text(host_base: str) -> str:
    """Fetch the manifest.json currently deployed on a host ("" on failure)."""
    try:
        with direct_urlopen(host_base + "/manifest.json", timeout=30) as r:
            return r.read().decode("utf-8").strip()
    except Exception:  # noqa: BLE001
        return ""


def push_to_modelscope(
    local_dir: Path, resources_dir: Path | None, files: dict[str, int], manifest: dict, dry: bool
) -> None:
    def src_of(p: str) -> Path:
        return (resources_dir / p[len("resources/"):]) if p.startswith("resources/") else local_dir / p

    remote = ms_remote_files()
    changed = sorted(p for p, s in files.items() if remote.get(p) != s)

    new_manifest_text = json.dumps(manifest, indent=2, ensure_ascii=False).strip()
    manifest_changed = remote_manifest_text(MANIFEST_HOSTS["ms"]["base"]) != new_manifest_text

    extra = sorted(set(remote) - set(files) - {"manifest.json", ".gitattributes"})
    if extra:
        log(f"warn: remote-only files on ModelScope (NOT deleted): {extra}")

    if not changed and not manifest_changed:
        log("ModelScope already up to date")
        return

    log(f"ModelScope: {len(changed)} file(s) + manifest.json (manifest changed: {manifest_changed})")
    for p in changed:
        log(f"  - {p} ({files[p]} bytes)")
    if dry:
        return

    user, token = ms_credentials()
    work = Path(tempfile.mkdtemp(prefix="ms-sync-"))
    env = {**os.environ, "GIT_LFS_SKIP_SMUDGE": "1"}

    # LFS 稳定性参数：
    # - concurrenttransfers=1：默认并行上传在大文件（GB 级）+ 代理/TUN 环境下
    #   易触发 Windows 端口耗尽（connectex 10048）或对端限流，单线程最稳
    # - locksverify=false：ModelScope 不支持 LFS locking API，避免每次探测
    # - SYNC_GIT_PROXY（可选）：显式 http.proxy 注入，绕过 TUN 的 fake-IP 直连
    #   （例：SYNC_GIT_PROXY=http://127.0.0.1:7890）
    git_extra: list[str] = [
        "-c", "lfs.concurrenttransfers=1",
        "-c", "lfs.locksverify=false",
        "-c", "lfs.activitytimeout=120",
        "-c", "lfs.dialtimeout=60",
    ]
    proxy = os.environ.get("SYNC_GIT_PROXY", "").strip()
    if proxy:
        git_extra += ["-c", f"http.proxy={proxy}"]
        log(f"using explicit git http proxy: {proxy}")

    try:
        url = f"https://{user}:{token}@www.modelscope.cn/{MS_REPO}.git"
        run(["git", *git_extra, "clone", "--depth", "1", url, str(work)], env=env)

        # Ensure big files of unknown extensions go through LFS. Use
        # `git lfs track` — the canonical writer — instead of hand-editing
        # .gitattributes (manual newline handling corrupted the file once and
        # silently broke LFS tracking -> modelscope push rejection).
        need = {
            f"*{p[p.rfind('.'):]}"
            for p in changed
            if p.rfind(".") > 0 and files[p] > LFS_THRESHOLD
        }
        for pattern in sorted(need):
            run(["git", "lfs", "track", pattern], cwd=work)

        for p in changed:
            dst = work / p
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_of(p), dst)
        (work / "manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        run(["git", "add", "-A"], cwd=work)
        run(["git", "commit", "-m", "Sync models from local directory"], cwd=work)
        run(["git", *git_extra, "push", "origin", "master"], cwd=work, env=env)
        # keep the token out of the on-disk remote url before cleanup
        run(["git", "remote", "set-url", "origin", f"https://www.modelscope.cn/{MS_REPO}.git"], cwd=work)
        log("ModelScope push done")
    finally:
        shutil.rmtree(work, ignore_errors=True)


def push_to_huggingface(
    local_dir: Path, resources_dir: Path | None, files: dict[str, int], manifest: dict, dry: bool
) -> None:
    from huggingface_hub import HfApi

    def src_of(p: str) -> Path:
        return (resources_dir / p[len("resources/"):]) if p.startswith("resources/") else local_dir / p

    api = HfApi()
    try:
        remote = {
            f.rfilename: (f.size or 0)
            for f in api.list_repo_tree(HF_REPO, repo_type="model", recursive=True)
            if hasattr(f, "size")
        }
    except Exception as e:  # noqa: BLE001
        log(f"warn: cannot list HF repo ({e}); uploading everything")
        remote = {}

    changed = sorted(p for p, s in files.items() if remote.get(p) != s)
    new_manifest_text = json.dumps(manifest, indent=2, ensure_ascii=False).strip()
    manifest_changed = remote_manifest_text(MANIFEST_HOSTS["hf"]["base"]) != new_manifest_text
    if not changed and not manifest_changed:
        log("HuggingFace already up to date")
        return
    log(f"HuggingFace: {len(changed)} file(s) + manifest.json (manifest changed: {manifest_changed})")
    for p in changed:
        log(f"  - {p}")
    if dry:
        return
    try:
        for p in changed:
            api.upload_file(
                path_or_fileobj=str(src_of(p)),
                path_in_repo=p,
                repo_id=HF_REPO,
                repo_type="model",
                commit_message=f"sync {p}",
            )
        api.upload_file(
            path_or_fileobj=str(local_dir / "manifest.json"),
            path_in_repo="manifest.json",
            repo_id=HF_REPO,
            repo_type="model",
            commit_message="sync manifest.json",
        )
        log("HuggingFace push done")
    except Exception as e:  # noqa: BLE001
        log(f"warn: HF upload failed ({e}). A *write* token is required: "
            "https://huggingface.co/settings/tokens -> save to ~/.cache/huggingface/token")


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync local models dir to ModelScope + HF")
    ap.add_argument("--local-dir", default=".ai00-x-dev/models", help="local models directory")
    ap.add_argument(
        "--resources-dir",
        default=None,
        help="build dist dir with installer resource zips (uploaded under resources/)",
    )
    ap.add_argument("--skip-ms", action="store_true", help="skip ModelScope upload")
    ap.add_argument("--skip-hf", action="store_true", help="skip HuggingFace upload")
    ap.add_argument(
        "--only-resources",
        action="store_true",
        help="upload only resources/* zips (models assumed already synced)",
    )
    ap.add_argument("--dry-run", action="store_true", help="print changes, upload nothing")
    args = ap.parse_args()

    local_dir = Path(args.local_dir).resolve()
    if not local_dir.is_dir():
        log(f"local dir not found: {local_dir} (pass --local-dir)")
        return 1

    resources_dir = Path(args.resources_dir).resolve() if args.resources_dir else None
    if resources_dir is not None and not resources_dir.is_dir():
        log(f"resources dir not found: {resources_dir}")
        return 1

    files = collect_local_files(local_dir)
    if not files:
        log(f"no model files under {local_dir}")
        return 1
    if resources_dir is not None:
        res = collect_resource_files(resources_dir)
        if not res:
            log(f"warn: no resource zips found under {resources_dir}")
        files.update(res)
    if args.only_resources:
        files = {p: s for p, s in files.items() if p.startswith("resources/")}
        if not files:
            log("no resources/* files to upload (pass --resources-dir)")
            return 1
    log(f"{len(files)} local file(s), {sum(files.values()) / 1e9:.2f} GB total")

    if args.only_resources:
        # Keep the existing model manifest untouched (files was filtered to
        # resources/* only — rebuilding from it would wipe the components).
        manifest = load_existing_manifest(local_dir)
        log(f"only-resources: manifest left as-is ({len(manifest.get('components', {}))} components)")
    else:
        manifest = build_manifest(local_dir, files, load_existing_manifest(local_dir))
        (local_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        log(f"manifest.json written ({len(manifest['components'])} components)")

    if not args.skip_ms:
        push_to_modelscope(local_dir, resources_dir, files, manifest, args.dry_run)
    if not args.skip_hf:
        push_to_huggingface(local_dir, resources_dir, files, manifest, args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
