//! Per-session rolling summary for context-aware smart routing.
//!
//! Each conversation keeps a short rolling summary generated by the resident
//! rwkv-local engine using the OFFICIAL RWKV7-G1 template (material first,
//! Question/Answer), byte-exact formatting and deterministic decoding.
//! The prompt/params/cleaning below are FROZEN — the training-data generator
//! (`rwkv-rsv/examples/batch_summarize.rs`) must stay in lockstep.
//!
//! Format notes (RWKV is newline/space sensitive, see RWKV7-G1x-templates):
//! - all inputs pass `clean_txt` (CRLF -> LF, collapse runs of newlines)
//! - material block, then `\n\n`, then `Question: ...\nAnswer:`
//! - deterministic decoding (temperature ~0): the first one or two sentences
//!   are reliable; long-tail repetition is cut by `clean_summary`
//!
//! Lifecycle: `update` is spawned after each successful dialog turn
//! (async, never blocks the chat path); `get` feeds the classifier on the
//! next turn. Missing summary (first turn / generation failure) simply
//! degrades to bare-request classification, which is a trained distribution.

use std::collections::{HashMap, HashSet, VecDeque};
use std::sync::{Mutex, OnceLock};

use ai00_x_ai_adapters::providers::rwkv::engine::get_rwkv_engine;
use log::{debug, warn};

/// Upper bound on cached summaries (oldest evicted, mirroring the sticky
/// tier table's LRU).
const SUMMARY_CACHE_LIMIT: usize = 512;
/// Max new tokens for one summary generation. The first sentences carry the
/// task signal; the rest is usually repetition and gets cut anyway.
const SUMMARY_MAX_TOKENS: usize = 96;
/// Word budget enforced by post-truncation.
const SUMMARY_MAX_WORDS: usize = 120;
/// Assistant reply head fed into the prompt (keeps prompt bounded).
const ASSISTANT_HEAD_CHARS: usize = 500;

/// 官方 clean_txt：CRLF 归一 + 连续换行压缩为单个（RWKV 对回车/换行敏感，
/// 见 RWKV7-G1x-templates.txt）。所有进入 prompt 的文本必须先过这里。
pub fn clean_txt(txt: &str) -> String {
    let normalized = txt.replace("\r\n", "\n").replace('\r', "\n");
    let mut out = String::with_capacity(normalized.len());
    let mut last_nl = false;
    for ch in normalized.chars() {
        if ch == '\n' {
            if !last_nl {
                out.push('\n');
            }
            last_nl = true;
        } else {
            out.push(ch);
            last_nl = false;
        }
    }
    out.trim().to_string()
}

/// 官方 RWKV7-G1 格式（材料在前 + Question/Answer，字节级对齐模板）。
/// 定稿冻结：训练数据生成器（batch_summarize.rs）必须逐字一致。
pub fn build_summary_prompt(
    prev_summary: Option<&str>,
    last_user: &str,
    last_assistant: &str,
) -> String {
    let prev = prev_summary
        .map(clean_txt)
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "(none)".to_string());
    let user = clean_txt(last_user);
    let assistant_head: String = clean_txt(last_assistant)
        .chars()
        .take(ASSISTANT_HEAD_CHARS)
        .collect();
    format!(
        "Conversation so far:\nSummary: {prev}\nUser: {user}\nAssistant: {assistant_head}\n\nQuestion: Summarize the conversation. What task is in progress?\nAnswer:",
    )
}

/// Post-processes a generated summary: strips prompt echo, cuts at the first
/// double newline, detects repetition degeneration (3-gram re-occurrence),
/// keeps at most the first two sentences, enforces the word budget.
pub fn clean_summary(raw: &str) -> Option<String> {
    let mut text = raw.trim().to_string();
    // Drop common base-model echoes of the prompt scaffolding.
    for marker in ["Answer:", "Summary:", "Question:"] {
        if let Some(rest) = text.strip_prefix(marker) {
            text = rest.trim().to_string();
        }
    }
    // Cut at the first double newline — echo continuations follow it.
    if let Some(pos) = text.find("\n\n") {
        text.truncate(pos);
    }
    // Repetition degeneration (wide match): any 3-gram re-occurring later
    // marks the start of a loop ("the crate may be changed" variants).
    let words: Vec<&str> = text.split_whitespace().collect();
    let mut cut = words.len();
    if words.len() >= 12 {
        'outer: for i in 3..words.len().saturating_sub(3) {
            let gram = &words[i - 3..i];
            if words[i + 3..].windows(3).any(|w| w == gram) {
                cut = (i - 1).max(1);
                break 'outer;
            }
        }
    }
    let mut text: String = words[..cut.min(words.len())].join(" ");
    // Sentence-level truncation (char-boundary safe: multi-byte sentence
    // endings like '。' must not be cut with byte +1).
    let sentence_ends: Vec<usize> = text
        .char_indices()
        .filter(|(_, c)| matches!(c, '.' | '。' | '!' | '？' | '?'))
        .map(|(i, c)| i + c.len_utf8())
        .collect();
    if let Some(&first_end) = sentence_ends.first() {
        let keep_to = match sentence_ends.get(1) {
            Some(&second_end) if second_end - first_end <= 60 && second_end < text.len() => {
                second_end
            }
            _ => first_end,
        };
        text.truncate(keep_to);
    }
    // Word budget (whitespace words; CJK counts per char).
    let mut words = 0usize;
    let mut out = String::new();
    for ch in text.chars() {
        if ch.is_whitespace() || ch > '\u{2E80}' {
            words += 1;
        }
        if words > SUMMARY_MAX_WORDS {
            break;
        }
        out.push(ch);
    }
    let cleaned = out.trim().to_string();
    if cleaned.is_empty() {
        None
    } else {
        Some(cleaned)
    }
}

/// Global per-session summary cache (LRU) with in-flight dedup.
pub struct SessionSummaryService {
    summaries: Mutex<HashMap<String, String>>,
    order: Mutex<VecDeque<String>>,
    in_flight: Mutex<HashSet<String>>,
}

impl Default for SessionSummaryService {
    fn default() -> Self {
        Self::new()
    }
}

impl SessionSummaryService {
    pub fn new() -> Self {
        Self {
            summaries: Mutex::new(HashMap::new()),
            order: Mutex::new(VecDeque::new()),
            in_flight: Mutex::new(HashSet::new()),
        }
    }

    /// Current summary for the session (empty → bare-request classification).
    pub fn get(&self, session_id: &str) -> Option<String> {
        let table = self.summaries.lock().unwrap_or_else(|e| e.into_inner());
        table.get(session_id).cloned()
    }

    /// Asynchronously regenerates the summary after a completed turn.
    /// Skips when an update for the session is already running; failures keep
    /// the previous summary (or stay summary-less on the first turn).
    pub fn spawn_update(&self, session_id: &str, last_user: String, last_assistant: String) {
        {
            let mut in_flight = self.in_flight.lock().unwrap_or_else(|e| e.into_inner());
            if !in_flight.insert(session_id.to_string()) {
                debug!("[router-summary] update already in flight: {}", session_id);
                return;
            }
        }
        let prev = self.get(session_id);
        let prompt = build_summary_prompt(prev.as_deref(), &last_user, &last_assistant);
        let service = get_global_summary_service();
        let session = session_id.to_string();
        tokio::spawn(async move {
            let result = generate_summary(prompt).await;
            let mut in_flight = service.in_flight.lock().unwrap_or_else(|e| e.into_inner());
            in_flight.remove(&session);
            drop(in_flight);
            match result {
                Some(summary) => service.store(&session, summary),
                None => warn!(
                    "[router-summary] generation failed, keeping previous state: {}",
                    session
                ),
            }
        });
    }

    fn store(&self, session_id: &str, summary: String) {
        let mut table = self.summaries.lock().unwrap_or_else(|e| e.into_inner());
        let mut order = self.order.lock().unwrap_or_else(|e| e.into_inner());
        if table.contains_key(session_id) {
            order.retain(|k| k != session_id);
        } else {
            while table.len() >= SUMMARY_CACHE_LIMIT {
                match order.pop_front() {
                    Some(key) => {
                        table.remove(&key);
                    }
                    None => break,
                }
            }
        }
        order.push_back(session_id.to_string());
        let words = summary.split_whitespace().count();
        table.insert(session_id.to_string(), summary);
        debug!(
            "[router-summary] updated ({} words-ish): session={}",
            words, session_id
        );
    }
}

/// Runs one summary generation through the resident rwkv-local engine.
/// Params are FROZEN (deterministic decoding — temperature/top_p are advisory
/// here; the desktop engine path pins its own sampler, see rwkv_engine_adapter).
async fn generate_summary(prompt: String) -> Option<String> {
    let engine = get_rwkv_engine()?;
    if !engine.is_initialized() {
        return None;
    }
    let raw = engine
        .infer(
            prompt,
            SUMMARY_MAX_TOKENS,
            0.0, // deterministic (G1 recommendation)
            1.0,
            vec!["\n\nUser:".to_string(), "\n\nQuestion:".to_string()],
        )
        .await
        .ok()?;
    clean_summary(&raw)
}

static GLOBAL_SUMMARY_SERVICE: OnceLock<SessionSummaryService> = OnceLock::new();

/// Returns the global summary service singleton.
pub fn get_global_summary_service() -> &'static SessionSummaryService {
    GLOBAL_SUMMARY_SERVICE.get_or_init(SessionSummaryService::new)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prompt_is_official_g1_format() {
        let p = build_summary_prompt(Some("Translating a Rust doc"), "改成中文", "好的，已翻译。");
        // Material first, then blank line, then Question/Answer lines.
        assert!(p.starts_with("Conversation so far:\nSummary: Translating a Rust doc\n"));
        assert!(p.contains("\n\nQuestion: Summarize the conversation. What task is in progress?\nAnswer:"));
        assert!(p.ends_with("Answer:"));

        let first = build_summary_prompt(None, "hello", "hi");
        assert!(first.contains("Summary: (none)"));
    }

    #[test]
    fn clean_txt_collapses_newlines_and_crlf() {
        assert_eq!(clean_txt("a\r\n\r\nb\n\n\nc"), "a\nb\nc");
        assert_eq!(clean_txt("  x  "), "x");
    }

    #[test]
    fn prompt_truncates_long_assistant_reply() {
        let long_assistant = "z".repeat(2000);
        let p = build_summary_prompt(None, "q", &long_assistant);
        // Prompt stays bounded: template + at most ASSISTANT_HEAD_CHARS of reply.
        assert!(p.len() < 1024, "prompt len {}", p.len());
        assert!(p.matches('z').count() <= ASSISTANT_HEAD_CHARS + 1);
    }

    #[test]
    fn clean_strips_echo_and_cuts_repetition() {
        assert_eq!(
            clean_summary("Answer: Task: fixing a login bug."),
            Some("Task: fixing a login bug.".to_string())
        );
        // Double newline cuts echo continuations.
        assert_eq!(
            clean_summary("Debug session about CUDA OOM.\n\nUser: next question"),
            Some("Debug session about CUDA OOM.".to_string())
        );
        // 3-gram repetition degeneration is cut at first occurrence.
        let degenerated = "The user is fixing a Rust FFI bug. the crate may be changed, the crate may be changed, the crate may be changed";
        let cleaned = clean_summary(degenerated).unwrap();
        assert!(cleaned.starts_with("The user is fixing a Rust FFI bug."));
        assert!(!cleaned.contains("the crate may be changed, the crate"));
        // Empty is rejected.
        assert_eq!(clean_summary("   \n  "), None);
        // Multi-byte sentence ending must not panic (char-boundary truncation).
        let zh = "用户正在调试内存泄漏问题。后续会继续分析堆转储。多余的内容。";
        let cleaned = clean_summary(zh).unwrap();
        assert!(cleaned.ends_with('。'));
        assert!(!cleaned.contains("多余"));
    }

    #[test]
    fn cache_lru_and_dedup() {
        let svc = SessionSummaryService::new();
        assert_eq!(svc.get("s1"), None);
        svc.store("s1", "first".to_string());
        assert_eq!(svc.get("s1"), Some("first".to_string()));
        svc.store("s1", "second".to_string());
        assert_eq!(svc.get("s1"), Some("second".to_string()));
    }
}
